name: Deploy Nginx to Master Clusters

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Push Docker Image
      run: |
        docker build -t lshworkspace-nginx .
        docker tag lshworkspace-nginx lshworkspace/lshworkspace-nginx:latest
        echo ${{ secrets.DOCKER_TOKEN }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push lshworkspace/lshworkspace-nginx:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}

    - name: SSH to Master cluster
      uses: appleboy/ssh-action@v0.5.4
      with:
        host: ${{ secrets.SERVER_IPADDR }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull lshworkspace/lshworkspace-nginx:latest
          docker stop lshworkspace-nginx-container || true
          docker rm lshworkspace-nginx-container || true
          docker run -d -p 80:80 --name lshworkspace-nginx-container lshworkspace/lshworkspace-nginx:latest
